#!/bin/bash
# nuke and recreate the current repo

AUTHOR="Anonymous <anonymous@localhost>"  # protects private email
SIGNER="1F517725"

if [[ $# -eq 0 ]]; then echo "Usage: nuke_repo <path/to/repo>"; exit 1; fi
echo "Chosen repo: $(readlink -f $1)"

git status 1>/dev/null 2>/dev/null
if ! [[ $? == 0 ]]; then echo "$DIR: not a repo!"; exit -1; fi

git pull 1>/dev/null 2>/dev/null
if ! [[ $? == 0 ]]; then
    read -p "Pull test failed! Continue? [y/N]: " VAR
    if ! [[ $VAR =~ [Yy] ]]; then exit; fi
fi

read -p "Use anonymous author? [y/N]: " VAR
if [[ $VAR =~ [Yy] ]]; then
	AUTHOR_STR="--author=\"$AUTHOR\""
	echo "Using author: $AUTHOR"
fi

read -p "Sign commit? [y/N]: " VAR
if [[ $VAR =~ [Yy] ]]; then
	read -p "Signer [$SIGNER]: " VAR
	if ! [[ -z $VAR ]]; then SIGNER=$VAR; fi
	SIGN_STR="--gpg-sign=$SIGNER"
	echo "Signing with: $SIGNER $(gpg -K $SIGNER | grep -o "<\+.*\+>" | head -n1)"
fi

echo "####################################################################"
echo " WARNING: ALL PRIOR COMMITS (BOTH LOCAL AND REMOTE) WILL BE LOST!!! "
echo "####################################################################"
echo "To avoid data loss, confirm file changes before proceeding."
read -p "Continue? [y/N]: " VAR
if ! [[ $VAR =~ [Yy] ]]; then exit; fi

ORIGIN=$(git remote get-url origin)
rm -rf .git
git init
git remote add origin $ORIGIN
git add --all
eval "git commit $AUTHOR_STR $SIGN_STR -m 'nuked'"  # git takes expanded var as input??
git push -f -u origin master
